### ISSUE TITLE
Missing Repo

### ISSUE THREAD

**Issue by simon-donike** [eo4geocourses/metadata_scraper#13]
What happenend to the SpaSe_OBIA-for-Operations-Copernicus-Service-Challenge-Practical-Example/ repo? Was it deleted?

**Comment by hoferb** [comment]
SpaSe contributed the Urban Heat Islands example - I am not aware of a second repository from them.

**Comment by simon-donike** [comment]
Seems like the Repo was renamed to Urban Heat islands a while ago and the link was an artifact of that. Everything fixed.
